### PR TITLE
change make_student_of! to receive a string instead of an object

### PR DESCRIPTION
**Pull request by julian-berbel**
Related to mumuki/mumuki-laboratory#1094.

### CODE REVIEW

**Comment by flbulgarelli** [comment]
I don't get the semantic difference between `enrol_in` and `make_student_of!`. They just differ in the arguments they expect, but the name does not denote that.

**Comment by flbulgarelli** [comment]
That is why I proposed to create a `accept_invitation` that only worked for invitations. And have `enrol_in` for courses.

**Comment by flbulgarelli** [comment]
However, I have just noticed that `make_student_of` does not really take an organization nor a course, but anything that understands a slug. The problem is that invitations don't expose a curse object, but just a string. So you should

1. implement `accept_invitation!` as proposed earlier; or
2. make `make_student_of!` work with plain slugs, too. This is a little uglier, but it doesn't polute the namespace with methods with similar semantics and not very different names like here. Something like this: 

```ruby
def make_student_of!(slug_like)
  slug = slug_like.is_a? String ? slug_like : slug_like.slug
  add_permission! :student, slug
end
```

Also, rename `make_student_of!` to `enrol_in!` if you prefer.

**Comment by julian-berbel** [comment]
> implement accept_invitation! as proposed earlier; or

I'm not sure I understand what you mean with this option. As you said, Invitation>>course is a String, so doing something like `user.make_student_of! invitation.course` fails because strings do not understand `slug`.

I was planning on adding `enrol_in!` which takes a slug string instead of an object and using that method instead of `make_student_of!` in `accept_invitation!`.

That being said, we don't seem to be using `make_student_of!` anywhere other than for accepting invitations, so wouldn't it be ok to just revert it to its original implementation which was taking a slug string instead of an object, and scrapping `enrol_in!`?

I don't really mind about its current name, I just needed it to be something different. I just used enrol_in! because of its similar meaning.

**Pull request merged**
